version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: es01
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/tmp/es01-data
    ports:
      - 9200:9200
    networks:
      - nw-crud-challenge


  crud-backend:
    build:
      context: ./crud-backend
    image: crud-backend
    container_name: crud-backend
    environment:
      - de.torstenkohn.crud.elasticsearch.host=es01
    ports:
      - 8080:8080
    expose:
      - "8080"
    networks:
      - nw-crud-challenge
    depends_on:
      - es01


volumes:
  data01:
    driver: local


networks:
  nw-crud-challenge:
    driver: bridge